Mvc/Models/FlightDataModel.cs
using System;
using System.Web;
using System.Web.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Newtonsoft.Json;
using SpaceXWidget.Mvc.ViewModels;

namespace SpaceXWidget.Mvc.Models
{
    public class FlightDataModel
    {
        public List<string[]> GetViewModel() => Task.Run(() => this.GetLaunchAsync()).Result;

        private async Task<List<string[]>> GetLaunchAsync()
        {
            using (var client = new HttpClient())
            {
                var response = await client.GetAsync("https://api.spacexdata.com/v4/launches");
                response.EnsureSuccessStatusCode();
                var jsonString = await response.Content.ReadAsStringAsync();

                var deserializedList = JsonConvert.DeserializeObject<List<LaunchViewModel>>(jsonString);

                List <string[]> aircraftInformation = new List<string[]>();

                foreach (var objectInList in deserializedList)
                {
                    string[] information = new string[2];
                    information[0] = objectInList.Id;
                    information[1] = objectInList.Name;
                    aircraftInformation.Add(information);
                }

                return aircraftInformation;
            }
        }
    }
}

Mvc/Models/PickIDModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SitefinityWebApp.Mvc.Models
{
    public class PickIDModel
    {
    }
}

Mvc/ViewModels/IDModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SitefinityWebApp.Mvc.ViewModels
{
    public class IDModel
    {
    }
}

Mvc/ViewModels/LaunchViewModel.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SpaceXWidget.Mvc.ViewModels
{
    public class LaunchViewModel
    {
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        [JsonProperty(PropertyName = "launchpad")]
        public string LaunchpadNumber { get; set; }

        [JsonProperty(PropertyName = "links")]
        public LinkViewModel Links { get; set; }

        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }
    }

    public class LinkViewModel
    {
        public PatchViewModel Patch { get; set; }

        [JsonProperty(PropertyName = "webcast")]
        public string VideoToWatch { get; set; }
    }

  
    public class PatchViewModel
    {
        [JsonProperty(PropertyName = "large")]
        public string Large { get; set; }

        [JsonProperty(PropertyName = "small")]
        public string Small { get; set; }
    }
}

Mvc/Controllers/FlightDataController.cs
/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.29
</auto-generated>
------------------------------------------------------------------------------ */

using Newtonsoft.Json;
using System;
using SpaceXWidget.Mvc.Models;
using SpaceXWidget.Mvc.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Net.Http;
using Telerik.Sitefinity.Mvc;
using Telerik.Sitefinity.Personalization;
using System.Threading.Tasks;
using System.Net;

namespace SpaceXWidget.Mvc.Controllers
{
	[ControllerToolboxItem(Name = "FlightData_MVC", Title = "Space X Latest Flight Updated", SectionName = "SpaceX")]
	public class FlightDataController : Controller, IPersonalizable
	{
        List<string[]> aircraftInformation;
        List<string[]> aircraftInformationSafeCopy;
        public FlightDataController()
        {
            var flightDataModel = new FlightDataModel();
            aircraftInformation = flightDataModel.GetViewModel();
            aircraftInformationSafeCopy = aircraftInformation;            
        }

        // GET: FlightData
        public ActionResult Index()
		{
            ViewBag.aircraftInformation = aircraftInformation.OrderBy(x => x[1]).ToList();      
            return View(); 
		}

        public ActionResult OrderByFirstLetter(bool sortOrder)
        {         
            if (sortOrder)
            {
                aircraftInformation = aircraftInformation.OrderBy(x => x[1]).ToList();
            } else
            {
                aircraftInformation = aircraftInformation.OrderByDescending(x => x[1]).ToList();
            }
                
            ViewBag.aircraftInformation = aircraftInformation;
            return View("Index");
        }

        [HttpPost]
        public ActionResult SearchSpecificString(string searchString)
        {
            if (!String.IsNullOrEmpty(searchString))
            {
                aircraftInformation = aircraftInformation.Where(s => s[1].Contains(searchString)).ToList();
            }
         
            ViewBag.aircraftInformation = aircraftInformation;
            return View("Index");
        }

        public ActionResult LaunchDetails(string aircraftID)
        {
            bool IDExists = false;
            foreach (var aircraft in aircraftInformation)
            {
                if (aircraft[0] == aircraftID)
                {
                    IDExists = true;
                    break;
                }
            }

            if (!IDExists)
            {
                return View("NotFound");
            }

            var client = new HttpClient();                     
            var jsonString = (new WebClient()).DownloadString("https://api.spacexdata.com/v4/launches/" + aircraftID);
            var deserialiedViewModel = JsonConvert.DeserializeObject<LaunchViewModel>(jsonString);

            return View(deserialiedViewModel);           
        }

        public string Message { get; set; }
	}
}

Mvc/Views/FlightData/IDIndex.cshtml
<!--This is the initial version of the SpaceX API widget. In the following code the user was presented to a specific spacecraft-->

@model SitefinityWebApp.Mvc.ViewModels.LaunchViewModel

<div class="jumbotron">
    <h1>@Model.LaunchpadNumber - @Model.Name</h1>
    <h2> is the number of the launchpad from which the rocket was fired and its name </h2>

    <img src="@Model.Links.Patch.Small" alt="No rocket image today" />

    <a href="@Model.Links.VideoToWatch">This is a very cool video</a>

    <hr>
    <p> This is the current news id: @Model.Id </p>
    <hr>
</div>

Mvc/Views/FlightData/Index.cshtml
@model SpaceXWidget.Mvc.ViewModels.LaunchViewModel

<main>
    <p> Hello and welcome to our SpaceX API application! </p>

    @using (Html.BeginForm("SearchSpecificString", "FlightData"))
    {
        <p>
            Find by name: @Html.TextBox("SearchString")
            <input type="submit" value="Search" />
        </p>
    }

    <table>
        <tr>
            <th>
                @Html.ActionLink("Sort A-Z", "OrderByFirstLetter", new { sortOrder = "true" })
            </th>
            <th>
                @Html.ActionLink("Sort Z-A", "OrderByFirstLetter", new { sortOrder = "false" })
            </th>
        </tr>
    </table>

    <table>
        <tr>
            <td>
                <p class="left"> Aircraft name </p>
            </td>
            <td>
                <p class="right"> More information </p>
            </td>
        </tr>
    </table>

    @foreach (string[] property in @ViewBag.aircraftInformation)
    {
        <table>
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => property[1])
                </td>
                <td>
                    @Html.ActionLink("Aircraft Details", "LaunchDetails", new { aircraftID = property[0] })
                </td>
            </tr>
        </table>
    }
</main>

@using Telerik.Sitefinity.Frontend.Mvc.Helpers
@ASP.PartialExtensions.Partial(Html, "ServerContext", new Telerik.Sitefinity.Frontend.Mvc.Models.ServerContext())
@Html.StyleSheet(Url.WidgetContent("Content/styling.css"))


Mvc/Views/FlightData/LaunchDetails.cshtml
@model SpaceXWidget.Mvc.ViewModels.LaunchViewModel

@{
    ViewBag.Title = "Details";
}
<body>
    <div class="contentBlock">
        <h1>Details</h1>

        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.LaunchpadNumber)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LaunchpadNumber)
            </dd>
        </dl>

        <img src="@Model.Links.Patch.Small" alt="No rocket image today" />

        <p class="redirect">
            @Html.ActionLink("Back to List", "Index")
        </p>
    </div>
</body>

@using Telerik.Sitefinity.Frontend.Mvc.Helpers
@ASP.PartialExtensions.Partial(Html, "ServerContext", new Telerik.Sitefinity.Frontend.Mvc.Models.ServerContext())
@Html.StyleSheet(Url.WidgetContent("Content/styling.css"))

Mvc/Views/FlightData/NotFound.cshtml
@model SpaceXWidget.Mvc.ViewModels.LaunchViewModel

<div>
    <p class="errorMessage"> The provided ID is not in the database </p>

    <p class="redirect">
        @Html.ActionLink("Back to List", "Index")
    </p>
</div>

@using Telerik.Sitefinity.Frontend.Mvc.Helpers
@ASP.PartialExtensions.Partial(Html, "ServerContext", new Telerik.Sitefinity.Frontend.Mvc.Models.ServerContext())
@Html.StyleSheet(Url.WidgetContent("Content/styling.css"))